// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo7QSnrjey6Fa8KwcqLehyxkbnwyOU9eE',
    appId: '1:1096204089851:web:a62572fcb2f3553882735e',
    messagingSenderId: '1096204089851',
    projectId: 'tclub-backend-4bd6c',
    authDomain: 'tclub-backend-4bd6c.firebaseapp.com',
    storageBucket: 'tclub-backend-4bd6c.appspot.com',
    measurementId: 'G-454WX4089B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfADWryBVxm3uF_RTtYk8fQBR6JQMcNpM',
    appId: '1:1096204089851:android:0432a5033b152b7982735e',
    messagingSenderId: '1096204089851',
    projectId: 'tclub-backend-4bd6c',
    storageBucket: 'tclub-backend-4bd6c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7MuVR9ZD8EBSWPe_FrFaGFPdtBs6ixec',
    appId: '1:1096204089851:ios:098aa6ee0bf3bc4b82735e',
    messagingSenderId: '1096204089851',
    projectId: 'tclub-backend-4bd6c',
    storageBucket: 'tclub-backend-4bd6c.appspot.com',
    iosClientId: '1096204089851-1n1bk60imeh8lj9i1adv9498a806chir.apps.googleusercontent.com',
    iosBundleId: 'com.novi.tclub',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7MuVR9ZD8EBSWPe_FrFaGFPdtBs6ixec',
    appId: '1:1096204089851:ios:098aa6ee0bf3bc4b82735e',
    messagingSenderId: '1096204089851',
    projectId: 'tclub-backend-4bd6c',
    storageBucket: 'tclub-backend-4bd6c.appspot.com',
    iosClientId: '1096204089851-1n1bk60imeh8lj9i1adv9498a806chir.apps.googleusercontent.com',
    iosBundleId: 'com.novi.tclub',
  );
}
